#page title
page_title                                : Just Expenses             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/just-expenses-money-manager/id1373021367?itscg=30200&itsct=home_page&mttnsubad=1373021367 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=org.zerocode.justexpenses&referrer=utm_source%3Dhome_page # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Just Expenses # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Finances made simple # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple, tile-based ledger system for effortlessly visualizing and controlling your finances.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ZCT Labs                                
your_link                                 : mailto:zerocodeteam@gmail.com                     
your_city                                 : Novi Sad                                
email_address                             : zerocodeteam@gmail.com
facebook_username                         : #                                          
instagram_username                        : zerocodeteam
twitter_username                          : #ebaehr
github_username                           : #emilbaehr
youtube_username                          : #



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : See Where Your Money Goes
    description                           : Gain instant clarity on your spending habits. Identify leaks and discover exactly where your money is going so you can take control.
    fontawesome_icon_name                 : search-dollar

  - title                                 : Discover How Much You Can Save
    description                           : With insightful charts and reports, you’ll spot savings opportunities and track progress toward your financial goals with confidence.
    fontawesome_icon_name                 : chart-line

  - title                                 : Your Data Stays With You
    description                           : Your financial data never leaves your phone. It stays private, secure, and under your full control—no accounts or servers involved.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Share Financial Reports in Seconds
    description                           : Export your expenses with a tap—perfect for budgeting, taxes, or sharing with a partner. No hassle, just useful insights when you need them.
    fontawesome_icon_name                 : file-export

  - title                                 : Always Ready, Even Offline
    description                           : Track your finances anywhere, anytime. Whether you’re on a plane or in a remote location, the app works fully without internet.
    fontawesome_icon_name                 : plane

  - title                                 : Built for Everyday Use
    description                           : Whether you’re budgeting for groceries or planning a trip, Just Expenses helps you stay on track daily without overwhelming features.
    fontawesome_icon_name                 : calendar-check

  - title                                 : Customize to Fit Your Life
    description                           : Tailor your categories, icons, and colors to match your lifestyle. The app bends to your habits—not the other way around.
    fontawesome_icon_name                 : sliders-h

  - title                                 : Lightweight and Fast
    description                           : Don’t sacrifice speed or space. Our app runs smoothly on any phone and keeps things fast and responsive without draining your device.
    fontawesome_icon_name                 : feather-alt

  - title                                 : Evolving with Your Feedback
    description                           : We listen. Your ideas shape the future of the app, with frequent updates focused on improving your day-to-day money management.
    fontawesome_icon_name                 : comments
    
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#e9eff5"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman
