#page title
page_title                                : Just Expenses                             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/id1373021367 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=org.zerocode.justexpenses # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Just Expenses                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Simple expense tracker # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Do you know where your money goes? Most of us don't. Just Expenses™ is a product designed to help you better understand how you spend your money.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ZeroCode Team                                
your_link                                 : mailto:zerocodeteam@gmail.com                     
your_city                                 : Novi Sad                                
email_address                             : zerocodeteam@gmail.com
facebook_username                         : #                                          
instagram_username                        : #zerocodeteam
twitter_username                          : #ebaehr
github_username                           : #emilbaehr
youtube_username                          : #



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Keep your data safe
    description                           : Financial data are sensitive information, thus it is very important to understand where they are stored. With Just Expenses™ your data never leaves your phone. They are stored on device and only you have access to it.
    fontawesome_icon_name                 : mobile

  - title                                 : Offline is the new luxury
    description                           : No busy waiting for data to be loaded from a remote server. We designed an app to work offline from day one. All you need is right there, in your hands.
    fontawesome_icon_name                 : sync

  - title                                 : Less is more
    description                           : Our goal was to make a simple but powerful product to track spendings without compromising privacy. Having that in mind we developed an app that doesn't require any permission for running.
    fontawesome_icon_name                 : adjust

  - title                                 : Size does matter
    description                           : We also care about your storage. App download size is less than 2Mb. This is more than six times lower compared to other apps for managing money. For those of you who do not have flagship phones, don't worry. This product will shine on your phone too.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Always getting better
    description                           : Just Expenses™ is constantly being updated and improved. We are fully dedicated to bring the best experience to our users so help us stand out by sending your feedback. Download and start saving money now.
    fontawesome_icon_name                 : magic

  - title                                 : #Need any help
    description                           : #Don't hesitate to caontact us.
    fontawesome_icon_name                 : #link

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman