#page title
page_title                                : Just Expenses             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/id1373021367 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=org.zerocode.justexpenses # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Just Expenses # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Simple Personal Finance Tracker # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Manage your finances with simplicity and security. With an intuitive interface, easily track expenses and income without hassle. Your data stays private—never leaving your device—ensuring complete safety while you manage your finances effortlessly.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ZCT Labs                                
your_link                                 : mailto:zerocodeteam@gmail.com                     
your_city                                 : Novi Sad                                
email_address                             : zerocodeteam@gmail.com
facebook_username                         : #                                          
instagram_username                        : zerocodeteam
twitter_username                          : #ebaehr
github_username                           : #emilbaehr
youtube_username                          : #



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Keep Your Data Safe
    description                           : Financial data is highly sensitive, making it essential to know where it’s stored. With our app, your data remains secure on your device and never leaves your phone. Only you have access, ensuring complete control and peace of mind.
    fontawesome_icon_name                 : lock

  - title                                 : Full Offline Access
    description                           : No more waiting for data to load from remote servers. Our app was designed to work offline from day one, ensuring everything you need is right at your fingertips.
    fontawesome_icon_name                 : wifi

  - title                                 : Simplicity with Powe
    description                           : We aimed to create a product that is both simple and powerful. With this approach, we developed an app that runs seamlessly without needing any permissions.
    fontawesome_icon_name                 : adjust

  - title                                 : Small App, Big Performance
    description                           : We understand storage matters, especially for non-flagship phones. Our app is lightweight yet powerful, ensuring it runs smoothly and efficiently on any device.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Continuously Improving for You
    description                           : Our app is constantly updated to deliver the best experience possible. We’re committed to enhancing your journey, and your feedback helps us grow even further. Download now and start managing your finances effortlessly while saving money.
    fontawesome_icon_name                 : forward

  - title                                 : Your Ideas, Our Future
    description                           : We’re always looking for ways to improve. Share your feature suggestions with us, and help shape the app to better suit your needs. Your feedback drives our innovation!
    fontawesome_icon_name                 : comment

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman